### ISSUE TITLE
Win10 64位添加开机启动后不自动应用配置文件

### ISSUE THREAD

**Issue by 7HUGCk** [tindy2013/clashcmd#1]
作者你好，已经添加了配置文件且正常使用，apply_on_startup设置为真，Win10 64位专业版添加开机启动后重启不自动应用配置文件，还需要手动进行应用一次，进到配置文件管理中会显示：当前配置文件：XXX（是我自己命名的那个），不知道是不是我自身的问题，还望作者能解答一下，谢谢。

**Comment by tindy2013** [comment]
如果之前使用过旧版本添加启动项的话 更新后请重新添加

**Comment by 7HUGCk** [comment]
第一次使用的就是1.1.4版本。

**Comment by Mike-hd123** [comment]
可以复制一份配置文件到Profile中并命名为config.yaml

**Comment by n2day** [comment]
> 
> 
> 可以复制一份配置文件到Profile中并命名为config.yaml

**Comment by 7HUGCk** [comment]
> 
> 
> 可以复制一份配置文件到Profile中并命名为config.yaml

也不失为一种好办法，只是没有办法更新订阅了，先安排上吧，谢谢！

**Comment by Mike-hd123** [comment]
copy  App\subconverter\!filepath! Profile\config.yaml
大大可以在应用配置文件中添加这条代码
![image](https://user-images.githubusercontent.com/50143395/76373849-882d8300-637c-11ea-8b3b-e9e56209a76c.png)

**Comment by Mike-hd123** [comment]
随便添加一个可以自己配置的文件代码如下添加到如图
call inireader.bat :inireader_set "!sub_name!" "config" "config.ini"
![image](https://user-images.githubusercontent.com/50143395/76374018-f1ad9180-637c-11ea-881d-51c6ab267bda.png)

**Comment by tindy2013** [comment]
startup agent原来的设计就是模拟启动核心并应用配置文件  在不修改 config.yaml 的情况下仍然可以更新节点  这样与 Clash for Windows 的行为一致

**Comment by Mike-hd123** [comment]
> startup agent原来的设计就是模拟启动核心并应用配置文件 在不修改 config.yaml 的情况下仍然可以更新节点 这样与 Clash for Windows 的行为一致

但是你设置的恢复上次使用配置文件的设置不生效，只能通过复制到 config.yaml才可以开机时自行选择该配置文件，否则为默认的没有节点的配置文件。

**Comment by Mike-hd123** [comment]
在app文件夹新建vbs文件填写
createobject("wscript.shell").run "startup_agent.bat",0
然后将此文件快捷方式放到启动文件夹，即可解决黑色窗口以及，配置文件问题。

**Comment by 7HUGCk** [comment]
> 
> 
> 在app文件夹新建vbs文件填写
> createobject("wscript.shell").run "startup_agent.bat",0
> 然后将此文件快捷方式放到启动文件夹，即可解决黑色窗口以及，配置文件问题。

我试过了，启动黑屏没有了，但是还是不能自动应用配置文件，是不是win10权限的问题呢？

**Comment by Mike-hd123** [comment]
你可能需要确定一下pref.ini文件中
current_applied=配置文件名
说明是否存在。还有可以试试关闭clash后运行
App\startup_agent.bat
文件看看能否启动clash
startup_agent.bat是启动后运行clash并恢复原来的配置文件。
这个bug可能是磁盘载入慢于脚本的运行造成的。

**Comment by tindy2013** [comment]
本地测试脚本是没有问题的

**Comment by 7HUGCk** [comment]
> 
> 
> 你可能需要确定一下pref.ini文件中
> current_applied=配置文件名
> 说明是否存在。还有可以试试关闭clash后运行
> App\startup_agent.bat
> 文件看看能否启动clash
> startup_agent.bat是启动后运行clash并恢复原来的配置文件。
> 这个bug可能是磁盘载入慢于脚本的运行造成的。

你说的那个current_applied有我自己的配置文件名，而且http://127.0.0.1:9090/ui/#/proxies都可以载入，可以看到默认是网易云音乐那个配置，这说明clash是运行的吧，而且我看设置里系统代理都是配置好的。

**Comment by Mike-hd123** [comment]
是的，startup_agent.bat文件内是有恢复配置文件的代码的，不知道你的为什么没有运行。
你可以关闭clash然后在运行一下startup_agent.bat看看是否启动clash并启用配置文件，且你需要关闭原来的启动设置。

**Comment by 7HUGCk** [comment]
怎么折腾都不行，最后还是用这个方法吧。
复制一份配置文件到Profile中并命名为config.yaml

**Comment by shikkoku** [comment]
我遇到同样的问题，
