### ISSUE TITLE
更新配置失败

### ISSUE THREAD

**Issue by Masaiki** [tindy2013/clashcmd#2]
Generating artifact '-'...
Artifact '-' generate ERROR! Please check your link.
添加配置的时候是成功的
更新配置的时候总是会报这个错
之前选的是不通过subconverter转换
但无论如何都会启动 subconverter Generating artifact 不太清楚这里的作用

**Comment by oklong** [comment]
可以定时更新配置文件嘛

**Comment by oklong** [comment]
可以定时更新配置文件嘛
